version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '5000:3000'
    links:
      - mongo
    environment:
      DB_SERVER: mongo
      PORT: 3000

  mongo:
    container_name: mongo
    image: mongo:4.1.6
    ports:
      - '27017:27017'
